services:
  fastify-api-postgres:
    container_name: fastify-clean-arch-postgres
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fastify
